services:
  # Backend Service
  - type: web
    name: gei-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_HOST
        sync: false
      - key: DATABASE_PORT
        sync: false
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: DATABASE_NAME
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true

  # Frontend Service
  - type: web
    name: gei-frontend
    runtime: node
    rootDir: frontend
    buildCommand: npm ci --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        sync: false
      - key: NEXT_PUBLIC_WS_URL
        sync: false
      - key: NEXT_PUBLIC_APP_NAME
        value: "GEI Adeptify"
    healthCheckPath: /
    autoDeploy: true
